name: 🧪 Test Build

on:
  pull_request:
    branches: [ main, macos-build-test ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.gitignore'

jobs:
  test-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4
      
    - name: 🐍 Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: 📦 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: 🔍 Check Python dependencies
      run: |
        echo "🔍 Проверка Python зависимостей..."
        python3 -m pip install --upgrade pip
        
        # Проверяем основные зависимости
        if [ -f "requirements.txt" ]; then
          echo "📋 Основные зависимости:"
          cat requirements.txt
          pip install --dry-run -r requirements.txt
        fi
        
        # Проверяем PyQt зависимости
        if [ -f "pyqt_app/requirements.txt" ]; then
          echo "📋 PyQt зависимости:"
          cat pyqt_app/requirements.txt
          pip install --dry-run -r pyqt_app/requirements.txt
        fi
        
        # Проверяем скрипты зависимости
        if [ -f "scripts/requirements.txt" ]; then
          echo "📋 Скрипты зависимости:"
          cat scripts/requirements.txt
          pip install --dry-run -r scripts/requirements.txt
        fi
        
    - name: 🔍 Check Node.js dependencies
      run: |
        echo "🔍 Проверка Node.js зависимостей..."
        npm ci --dry-run
        
        echo "📋 Установленные пакеты:"
        npm list --depth=0
        
    - name: 🔨 Test TypeScript compilation
      run: |
        if [ -f "tsconfig.json" ]; then
          echo "🔨 Тестируем компиляцию TypeScript..."
          npx tsc --noEmit
          echo "✅ TypeScript проходит проверку типов"
        else
          echo "⚠️ tsconfig.json не найден"
        fi
        
    - name: 🔍 Check PyInstaller spec
      run: |
        if [ -f "macos_build/gosilk_staff.spec" ]; then
          echo "🔍 Проверка PyInstaller спецификации..."
          python3 -c "
          import ast
          with open('macos_build/gosilk_staff.spec', 'r') as f:
              content = f.read()
          # Проверяем синтаксис Python
          try:
              ast.parse(content)
              print('✅ PyInstaller spec синтаксически корректен')
          except SyntaxError as e:
              print(f'❌ Ошибка синтаксиса в spec файле: {e}')
              exit(1)
          "
        else
          echo "❌ gosilk_staff.spec не найден"
          exit 1
        fi
        
  test-structure:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4
      
    - name: 🔍 Check project structure
      run: |
        echo "🔍 Проверка структуры проекта..."
        
        # Проверяем обязательные файлы
        required_files=(
          "run_app.py"
          "requirements.txt"
          "package.json"
          "tsconfig.json"
          "macos_build/gosilk_staff.spec"
          "macos_build/build_macos.sh"
          "pyqt_app/main.py"
        )
        
        missing_files=()
        
        for file in "${required_files[@]}"; do
          if [ -f "$file" ]; then
            echo "✅ $file"
          else
            echo "❌ $file - ОТСУТСТВУЕТ"
            missing_files+=("$file")
          fi
        done
        
        if [ ${#missing_files[@]} -gt 0 ]; then
          echo ""
          echo "❌ Отсутствуют обязательные файлы:"
          printf '%s\n' "${missing_files[@]}"
          exit 1
        fi
        
        echo ""
        echo "✅ Все обязательные файлы найдены"
        
    - name: 🔍 Check Python imports
      run: |
        echo "🔍 Проверка Python импортов..."
        python3 -c "
        import sys
        sys.path.append('.')
        
        # Тестируем основные импорты
        try:
            import run_app
            print('✅ run_app.py импортируется')
        except ImportError as e:
            print(f'❌ Ошибка импорта run_app: {e}')
        
        try:
            from pyqt_app import main
            print('✅ pyqt_app.main импортируется')
        except ImportError as e:
            print(f'⚠️  pyqt_app.main требует PyQt6: {e}')
        
        try:
            from macos_build import resource_utils
            print('✅ macos_build.resource_utils импортируется')
        except ImportError as e:
            print(f'⚠️  macos_build.resource_utils: {e}')
        "
        
    - name: 📊 Generate test report
      run: |
        echo "📊 Отчет о тестировании структуры:"
        echo "================================="
        echo "🗂️  Структура каталогов:"
        find . -type d -name "__pycache__" -prune -o -type d -name "node_modules" -prune -o -type d -name ".git" -prune -o -type d -print | head -20
        echo ""
        echo "📄 Python файлы:"
        find . -name "*.py" -not -path "./__pycache__/*" -not -path "./node_modules/*" | head -10
        echo ""
        echo "📄 TypeScript файлы:"
        find . -name "*.ts" -not -path "./node_modules/*" | head -10
        echo ""
        echo "✅ Проверка структуры завершена" 